name: CI

on: [push]

jobs:
  prepare:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v1
      - name: Prepare
        run: |
          autoreconf -fi
          ./configure --without-python2-bindings

  cppcheck:
    needs: prepare
    runs-on: [self-hosted]
    steps:
      - name: cppcheck-confdb
        run: |
          [ -e reports ] || mkdir reports
          cppcheck --force --enable=information -I ./ -I src/ --std=c99 --enable=all --suppress=missingIncludeSystem --xml-version=2 src/db/ src/confdb/ src/krb5_plugin/ src/ldb_modules/ src/monitor/ src/p11_child/ src/providers/ src/python/ src/resolv/ src/responder/ src/sbus/ src/sss_client/ src/sss_iface/ src/tools/ src/util/ 2>reports/cppcheck.xml

  build:
    needs: prepare
    runs-on: [self-hosted]
    strategy:
      max-parallel: 2
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: |
          autoreconf -fi
          ./configure --without-python2-bindings
          make all
      - name: Documentation
        run: make docs

  tests:
    needs: build
    runs-on: [self-hosted]
    steps:
      - name: Build tests
        run: make tests

  run-tests:
    needs: tests
    runs-on: [self-hosted]
    steps:
      - name: Unit Tests
        run: |
          [ -e reports ] || mkdir reports
          RET=0
          for item in test-* test_*_* *-tests *_test *_tests
          do
              echo -e "\n>> $item"
              CMOCKA_MESSAGE_OUTPUT=xml LDB_MODULES_PATH=$PWD/ldb_mod_test_dir LD_LIBRARY_PATH=$PWD/.libs ./$item 1>reports/$item.xml 2>/tmp/test.out || (RET=1; cat /tmp/test.out)
          done
          exit $RET
