name: CI

on: [push]

jobs:
  prepare:
    runs-on: [self-hosted]
    steps:
    - uses: actions/checkout@v1
    - name: Prepare
      run: |
        autoreconf -fi
        ./configure --without-python2-bindings

  cppcheck:
    needs: prepare
    runs-on: [self-hosted]
    steps:
    - name: cppcheck-confdb
      run: |
        cppcheck --force --enable=information -I ./ -I src/ --std=c99 --enable=all --suppress=missingIncludeSystem --xml confdb/
        cppcheck --force --enable=information -I ./ -I src/ --std=c99 --enable=all --suppress=missingIncludeSystem --xml db/
        cppcheck --force --enable=information -I ./ -I src/ --std=c99 --enable=all --suppress=missingIncludeSystem --xml krb5_plugin/
        cppcheck --force --enable=information -I ./ -I src/ --std=c99 --enable=all --suppress=missingIncludeSystem --xml ldb_modules/
        cppcheck --force --enable=information -I ./ -I src/ --std=c99 --enable=all --suppress=missingIncludeSystem --xml monitor/
        cppcheck --force --enable=information -I ./ -I src/ --std=c99 --enable=all --suppress=missingIncludeSystem --xml p11_child/
        cppcheck --force --enable=information -I ./ -I src/ --std=c99 --enable=all --suppress=missingIncludeSystem --xml providers/
        cppcheck --force --enable=information -I ./ -I src/ --std=c99 --enable=all --suppress=missingIncludeSystem --xml python/
        cppcheck --force --enable=information -I ./ -I src/ --std=c99 --enable=all --suppress=missingIncludeSystem --xml resolv/
        cppcheck --force --enable=information -I ./ -I src/ --std=c99 --enable=all --suppress=missingIncludeSystem --xml responder/

  build:
    needs: prepare
    runs-on: [self-hosted]
    strategy:
      max-parallel: 2
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        autoreconf -fi
        ./configure --without-python2-bindings
        make all
    - name: Documentation
      run: make docs

  tests:
    needs: build
    runs-on: [self-hosted]
    steps:
    - name: Build tests
      run: make tests

  run-tests:
    needs: tests
    runs-on: [self-hosted]
    steps:
    - name: Unit Tests
      run: |
        RET=0; for item in test_*_*; do echo -e "\n>> $item"; LDB_MODULES_PATH=$PWD/ldb_mod_test_dir LD_LIBRARY_PATH=$PWD/.libs ./$item 1>/tmp/test.out 2>/tmp/test.out || (RET=1; cat /tmp/test.out); done; exit $RET
      
