name: CI

on: [push]

jobs:
  build:

    runs-on: fedora-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        dnf -y install git openssl sudo curl wget ruby rubygems "rubygem(json)" wget rpm-build dnf-plugins-core libldb-devel
        git clone --depth=50 --branch=master https://github.com/SSSD/sssd.git /tmp/sssd
        cd /tmp/sssd
        ./contrib/fedora/make_srpm.sh
        dnf builddep -y rpmbuild/SRPMS/sssd-*.src.rpm
        dnf -y clean all
        autoreconf -fi
        ./configure --without-python2-bindings
        make all
        make doc
        make tests
