name: CI

on: [push]

jobs:
  prepare:
    runs-on: [self-hosted]
    steps:
    - uses: actions/checkout@v1
    - name: Prepare
      run: |
        autoreconf -fi
        ./configure --without-python2-bindings

  build:
    needs: prepare
    runs-on: [self-hosted]
    strategy:
      max-parallel: 2
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        autoreconf -fi
        ./configure --without-python2-bindings
        make all
    - name: Documentation
      run: make docs

  tests:
    needs: build
    runs-on: [self-hosted]
    steps:
    - name: Build tests
      run: make tests

  run-tests:
    needs: tests
    runs-on: [self-hosted]
    steps:
    - name: Unit Tests
      run: |
        RET=0; for item in test_*_*; do echo -e "\n>> $item"; LDB_MODULES_PATH=$PWD/ldb_mod_test_dir LD_LIBRARY_PATH=$PWD/.libs ./$item || RET=1; done; exit $RET
      
