name: CI

on: [push]

jobs:
  prepare:
    runs-on: [self-hosted]
    steps:
    - uses: actions/checkout@v1
    - name: Prepare
      run: |
        autoreconf -fi
        ./configure --without-python2-bindings

  cppcheck:
    runs-on: [self-hosted]
    steps:
    - name: cppcheck-confdb
      run: cppcheck --force --enable=information -I ./ -I src/  --std=c99 --enable=all --suppress=missingIncludeSystem --xml confdb 2> junit-cpp-check-confdb.xml
    - name: publish-cppcheck-confdb-report
      uses: actions/upload-artifact@v1
      with:
        name: cppcheck-confdb-report
        path: junit-cpp-check-confdb.xml

    - name: cppcheck-db
      run: cppcheck --force --enable=information -I ./ -I src/ --std=c99 --enable=all --suppress=missingIncludeSystem --xml db 2> junit-cpp-check-db.xml
    - name: cppcheck-krb5_plugin
      run: cppcheck --force --enable=information -I ./ -I src/ --std=c99 --enable=all --suppress=missingIncludeSystem --xml krb5_plugin/ 2> junit-cpp-check-krb5_plugin.xml
    - name: cppcheck-ldb_modules
      run: cppcheck --force --enable=information -I ./ -I src/ --std=c99 --enable=all --suppress=missingIncludeSystem --xml ldb_modules/ 2> junit-cpp-check-ldb_modules.xml
    - name: cppcheck-monitor
      run: cppcheck --force --enable=information -I ./ -I src/ --std=c99 --enable=all --suppress=missingIncludeSystem --xml monitor/ 2> junit-cpp-check-monitor.xml
    - name: p11_child
      run: cppcheck --force --enable=information -I ./ -I src/ --std=c99 --enable=all --suppress=missingIncludeSystem --xml p11_child/ 2> junit-cpp-check-p11_child.xml
    - name: providers
      run: cppcheck --force --enable=information -I ./ -I src/ --std=c99 --enable=all --suppress=missingIncludeSystem --xml providers/ 2> junit-cpp-check-providers.xml
    - name: python
      run: cppcheck --force --enable=information -I ./ -I src/ --std=c99 --enable=all --suppress=missingIncludeSystem --xml python/ 2> junit-cpp-check-python.xml
    - name: resolv
      run: cppcheck --force --enable=information -I ./ -I src/ --std=c99 --enable=all --suppress=missingIncludeSystem --xml resolv/ 2> junit-cpp-check-resolv.xml
    - name: responder
      run: cppcheck --force --enable=information -I ./ -I src/ --std=c99 --enable=all --suppress=missingIncludeSystem --xml responder/ 2> junit-cpp-check-responder.xml

  build:
    needs: prepare
    runs-on: [self-hosted]
    strategy:
      max-parallel: 2
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        autoreconf -fi
        ./configure --without-python2-bindings
        make all
    - name: Documentation
      run: make docs

  tests:
    needs: build
    runs-on: [self-hosted]
    steps:
    - name: Build tests
      run: make tests

  run-tests:
    needs: tests
    runs-on: [self-hosted]
    steps:
    - name: Unit Tests
      run: |
        RET=0; for item in test_*_*; do echo -e "\n>> $item"; LDB_MODULES_PATH=$PWD/ldb_mod_test_dir LD_LIBRARY_PATH=$PWD/.libs ./$item 1>/tmp/test.out 2>/tmp/test.out || (RET=1; cat /tmp/test.out); done; exit $RET
      
