name: CI

on: [push]

jobs:
  build:
    runs-on: [self-hosted]
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        autoreconf -fi
        ./configure --without-python2-bindings
        make all
  doc:
    runs-on: [self-hosted]
    steps:
    - name: Documentation
      run: make doc
  tests:
    needs: build
    run-on: [self-hosted]
    steps:
    - name: Build tests
      run: make tests
  run-tests:
    needs: tests
    run-on: [self-hosted]
    steps:
    - name: Unit Tests
      run: echo "Running unit tests"
      
